# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usb_storage"
        "sd_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "none";
        fsType = "tmpfs";
        neededForBoot = true;
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/58F0-5509";
        fsType = "vfat";
    };

    fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/dbef62b9-e128-43e4-9450-d12e4a7cf6f9";
        fsType = "btrfs";
        options = [ "defaults" "ssd" "noatime" "compress-force=zstd" "subvol=@nix" ];
        neededForBoot = true;
    };

    boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/eafab863-832d-4609-980f-16c43660ed71";

    fileSystems."/persist" = {
        device = "/dev/disk/by-uuid/dbef62b9-e128-43e4-9450-d12e4a7cf6f9";
        fsType = "btrfs";
        options = [ "defaults" "ssd" "noatime" "compress-force=zstd" "subvol=@persist" ];
        neededForBoot = true;
    };

    fileSystems."/etc/nixos" = {
        device = "/dev/disk/by-uuid/dbef62b9-e128-43e4-9450-d12e4a7cf6f9";
        fsType = "btrfs";
        options = [ "defaults" "ssd" "noatime" "compress-force=zstd" "subvol=@nixos" ];
    };

    fileSystems."/var/log" = {
        device = "/dev/disk/by-uuid/dbef62b9-e128-43e4-9450-d12e4a7cf6f9";
        fsType = "btrfs";
        options = [ "defaults" "ssd" "noatime" "compress-force=zstd" "subvol=@log" ];
    };

    fileSystems."/data" = {
        device = "/dev/disk/by-uuid/dbef62b9-e128-43e4-9450-d12e4a7cf6f9";
        fsType = "btrfs";
        options = [ "defaults" "ssd" "noatime" "compress-force=zstd" "subvol=@data" ];
    };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
