# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fb537c4f-9db7-4bf0-a80d-b092a821c3bc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fb537c4f-9db7-4bf0-a80d-b092a821c3bc" = {
    device = "/dev/disk/by-uuid/fb537c4f-9db7-4bf0-a80d-b092a821c3bc";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };
  # Disk swap (p3 LUKS) retired in favour of zram (see configuration.nix). No hibernate.

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/97ED-3299";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "nosuid" "nodev" "noexec" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
